import { type DefaultCategory } from '../defaultDefinitions.js';

export const aiCategory: DefaultCategory = {
  id: 'ai',
  label: 'AI tool files',
  patterns: [
    '**/AGENTS.md',
    '**/AGENT.md',
    '**/CLAUDE.md',
    '**/GEMINI.md',
    '**/CONTEXT.md',
    'CLAUDE.local.md',
    '.mcp.json',
    '.worktreeinclude',
    '.ai',
    'boost.json',
    '**/.claude',
    '.cursorrules',
    '**/.cursor',
    '.cursorignore',
    '.cursorindexingignore',
    '.github/copilot-instructions.md',
    '.github/instructions',
    '.github/prompts',
    '.github/agents',
    '.windsurfrules',
    '.clinerules',
    '.clineignore',
    '.roomodes',
    '.rooignore',
    '.roorules',
    '.roo',
    '.aider.conf.yml',
    '.aiderignore',
    '.aider.model.settings.yml',
    '.aider.model.metadata.json',
    '**/AGENTS.override.md',
    '**/.codex',
    '.gemini',
    '.continue',
    '.kiro',
    '.junie',
    '.amazonq',
    '**/.augment',
    '.augment-guidelines',
    'opencode.json',
    'opencode.jsonc',
    '.opencode',
    '.agents',
    '.tabnine',
    '.supermavenignore',
    '.goosehints',
  ],
};
