import { type DefaultCategory } from '../defaultDefinitions.js';

export const ciCategory: DefaultCategory = {
  id: 'ci',
  label: 'CI and CD config',
  patterns: [
    '.github',
    '.gitlab-ci.yml',
    '.circleci',
    'azure-pipelines.yml',
    'Jenkinsfile',
    '.travis.yml',
    'bitbucket-pipelines.yml',
    '.drone.yml',
    'cloudbuild.yaml',
    '.buildkite',
    'appveyor.yml',
    'vercel.json',
    'netlify.toml',
    'fly.toml',
    'wrangler.toml',
    'wrangler.json',
    'wrangler.jsonc',
    'render.yaml',
    'railway.json',
    'railway.toml',
    'serverless.yml',
    'serverless.yaml',
    'app.yaml',
  ],
};
