import { type DefaultCategory } from '../defaultDefinitions.js';

export const lintCategory: DefaultCategory = {
  id: 'lint',
  label: 'Lint config',
  patterns: [
    '**/.eslintrc*',
    '**/eslint.config.*',
    '**/.eslintignore',
    '**/.stylelintrc*',
    '**/biome.json',
    '**/biome.jsonc',
    '**/.oxlintrc.json',
    '**/oxlint.config.*',
    '**/knip.json',
    '**/knip.jsonc',
    '**/knip.ts',
    '**/knip.config.*',
    '**/.markdownlint*',
    'cspell.json',
    '.cspell.json',
    'cspell.config.*',
    'sonar-project.properties',
    '.coderabbit.yaml',
    '.coderabbit.yml',
    '.size-limit*',
    '**/.jshintrc',
    '.trivyignore',
    '.trivyignore.yaml',
    '.trivyignore.yml',
    'trivy.yaml',
    '.snyk',
    '.semgrepignore',
    '.gitleaks.toml',
    '.gitleaksignore',
    '.checkov.yaml',
    '.checkov.yml',
    '.hadolint.yaml',
    '.hadolint.yml',
    '.secrets.baseline',
    '.flake8',
    'ruff.toml',
    '.ruff.toml',
    '.pylintrc',
    'clippy.toml',
    '.golangci.yml',
    '.golangci.yaml',
    '.rubocop.yml',
    'phpcs.xml',
    'phpcs.xml.dist',
    'checkstyle.xml',
    '.credo.exs',
    '.swiftlint.yml',
    '.clang-tidy',
    '.htmlhintrc',
  ],
};
