import { type DefaultCategory } from '../defaultDefinitions.js';

export const testCodeCategory: DefaultCategory = {
  id: 'testCode',
  label: 'Test code',
  patterns: [
    '**/__tests__',
    '**/__test__',
    '**/__mocks__',
    '**/__snapshots__',
    '**/__fixtures__',
    '**/test',
    '**/tests',
    '**/spec',
    '**/specs',
    '**/e2e',
    '**/testdata',
    '**/cypress',
    '**/*.test.*',
    '**/*.spec.*',
    '**/*.e2e.*',
    '**/*.cy.*',
    '**/*.snap',
    '**/*_test.go',
    '**/*_test.py',
    '**/test_*.py',
    '**/conftest.py',
    '**/*Test.java',
    '**/*Tests.java',
    '**/*Test.kt',
    '**/*Tests.cs',
    '**/*_test.rb',
    '**/*_spec.rb',
    '**/*_test.dart',
    '**/*_test.exs',
    '**/*Tests.swift',
  ],
};
